helloworld:	helloworld.c
	gcc -o helloworld  -Wall helloworld.c

all:	helloworld

help:
	@echo "type 'make' or 'make all' to compile"
	@echo "type 'make clean' to remove binaries"
clean:
	@rm -vf ./helloworld

